version: '3'
services:
  magic:
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
      KAGGLE_CONFIG_DIR: /home/src/secrets/
    ports:
      - 6789:6789
      - 4040:4040
    volumes:
      - .:/home/src/
      - ../secrets/:/home/src/secrets/
      - ../jars/:/home/src/jars/
    restart: on-failure:5
    stdin_open: true # docker run -i
    tty: true        # docker run -t
